Repository dictu-lang/Dictu, pull requests merged in 2020-03, with the labels that each got.

#146 Silence tcc compiler and add a return statement to exitNative().
  c/optionals/system.c
Labels: enhancement

#147 Make building the http class optional, as it requires libcurl (for no…
  .github/workflows/main.yml
  README.md
  c.make
  c/optionals/http.h
  c/vm.c
  tests/runTests.du
  tests/variables/magic.du
Labels: enhancement

#144 Add setCWD() method to the System class.
  c/optionals/system.c
  docs/docs/system.md
  tests/system/import.du
  tests/system/setCWD.du
Labels: enhancement

#152 Remove global VM variable
  c/chunk.c
  c/chunk.h
  c/common.h
  c/compiler.c
  c/compiler.h
  c/datatypes/copy.c
  c/datatypes/copy.h
  c/datatypes/dicts.c
  c/datatypes/dicts.h
  c/datatypes/files.c
  c/datatypes/files.h
  c/datatypes/instance.c
  c/datatypes/instance.h
  c/datatypes/lists.c
  c/datatypes/lists.h
  c/datatypes/sets.c
  c/datatypes/sets.h
  c/datatypes/strings.c
  c/datatypes/strings.h
  c/debug.c
  c/main.c
  c/memory.c
  c/memory.h
  c/natives.c
  c/natives.h
  c/object.c
  c/object.h
  c/optionals/env.c
  c/optionals/env.h
  c/optionals/http.c
  c/optionals/http.h
  c/optionals/json.c
  c/optionals/json.h
  c/optionals/math.c
  c/optionals/math.h
  c/optionals/optionals.c
  c/optionals/optionals.h
  c/optionals/system.c
  c/table.c
  c/table.h
  c/value.c
  c/value.h
  c/vm.c
  c/vm.h
Labels: enhancement

#155 Fix VM and GC
  c/chunk.c
  c/compiler.c
  c/compiler.h
  c/memory.c
  c/object.c
  c/optionals/http.c
  c/vm.c
  c/vm.h
Labels: bug fix

#154 Is defined
  c/natives.c
  c/vm.c
  docs/docs/built-ins.md
  tests/builtins/import.du
  tests/builtins/isDefined.du
  tests/runTests.du
Labels: enhancement

#156 Cache variables to avoid filling constants
  c/compiler.c
  c/compiler.h
Labels: enhancement

#157 Multiple assignment
  c/compiler.c
  docs/docs/variables.md
  tests/variables/assignment.du
Labels: enhancement

#158 Release 0.4.0
  .github/workflows/main.yml
  README.md
  c.make
  c/chunk.c
  c/chunk.h
  c/common.h
  c/compiler.c
  c/compiler.h
  c/datatypes/copy.c
  c/datatypes/copy.h
  c/datatypes/dicts.c
  c/datatypes/dicts.h
  c/datatypes/files.c
  c/datatypes/files.h
  c/datatypes/instance.c
  c/datatypes/instance.h
  c/datatypes/lists.c
  c/datatypes/lists.h
  c/datatypes/sets.c
  c/datatypes/sets.h
  c/datatypes/strings.c
  c/datatypes/strings.h
  c/debug.c
  c/main.c
  c/memory.c
  c/memory.h
  c/natives.c
  c/natives.h
  c/object.c
  c/object.h
  c/optionals/env.c
  c/optionals/env.h
  c/optionals/http.c
  c/optionals/http.h
  c/optionals/json.c
  c/optionals/json.h
  c/optionals/math.c
  c/optionals/math.h
  c/optionals/optionals.c
  c/optionals/optionals.h
  c/optionals/system.c
  c/scanner.c
  c/table.c
  c/table.h
  c/value.c
  c/value.h
  c/vm.c
  c/vm.h
  docs/_config.yml
  docs/docs/built-ins.md
  docs/docs/system.md
  docs/docs/variables.md
  tests/builtins/import.du
  tests/builtins/isDefined.du
  tests/runTests.du
  tests/system/import.du
  tests/system/setCWD.du
  tests/variables/assignment.du
  tests/variables/magic.du
Labels: release

#159 Garbage collection
  c/datatypes/dicts.c
  c/datatypes/instance.c
  c/datatypes/lists.c
  c/datatypes/sets.c
  c/value.c
  c/value.h
  tests/benchmarks/list-methods/join.du
Labels: bug fix, enhancement

#160 File closing
  c/compiler.c
  c/opcodes.h
  c/vm.c
Labels: enhancement

#161 Remove doubled "dict" logic as we can just use the Table type
  c/datatypes/copy.c
  c/datatypes/dicts.c
  c/memory.c
  c/memory.h
  c/natives.c
  c/object.c
  c/object.h
  c/optionals/http.c
  c/optionals/json.c
  c/table.c
  c/value.c
  c/value.h
  c/vm.c
Labels: enhancement

#164 Better method for native methods
  .gitignore
  c/datatypes/copy.c
  c/datatypes/copy.h
  c/datatypes/dicts.c
  c/datatypes/dicts.h
  c/datatypes/files.c
  c/datatypes/files.h
  c/datatypes/instance.c
  c/datatypes/instance.h
  c/datatypes/lists.c
  c/datatypes/lists.h
  c/datatypes/sets.c
  c/datatypes/sets.h
  c/datatypes/strings.c
  c/datatypes/strings.h
  c/memory.c
  c/natives.c
  c/natives.h
  c/optionals/env.c
  c/optionals/http.c
  c/optionals/json.c
  c/optionals/math.c
  c/optionals/optionals.c
  c/optionals/optionals.h
  c/optionals/system.c
  c/util.c
  c/util.h
  c/vm.c
  c/vm.h
Labels: enhancement

#166 Correctly free new tables
  c/compiler.c
  c/vm.c
Labels: bug fix

#165 Release 0.4.1
  .gitignore
  c/compiler.c
  c/datatypes/copy.c
  c/datatypes/copy.h
  c/datatypes/dicts.c
  c/datatypes/dicts.h
  c/datatypes/files.c
  c/datatypes/files.h
  c/datatypes/instance.c
  c/datatypes/instance.h
  c/datatypes/lists.c
  c/datatypes/lists.h
  c/datatypes/sets.c
  c/datatypes/sets.h
  c/datatypes/strings.c
  c/datatypes/strings.h
  c/main.c
  c/memory.c
  c/memory.h
  c/natives.c
  c/natives.h
  c/object.c
  c/object.h
  c/opcodes.h
  c/optionals/env.c
  c/optionals/http.c
  c/optionals/json.c
  c/optionals/math.c
  c/optionals/optionals.c
  c/optionals/optionals.h
  c/optionals/system.c
  c/table.c
  c/util.c
  c/util.h
  c/value.c
  c/value.h
  c/vm.c
  c/vm.h
  docs/_config.yml
  tests/benchmarks/list-methods/join.du
Labels: release

#167 Allow more value types to be dictionary keys
  c/compiler.c
  c/datatypes/copy.c
  c/datatypes/dicts.c
  c/memory.c
  c/memory.h
  c/natives.c
  c/object.c
  c/object.h
  c/opcodes.h
  c/optionals/http.c
  c/optionals/json.c
  c/util.c
  c/util.h
  c/value.c
  c/value.h
  c/vm.c
  docs/docs/collections.md
  tests/dicts/copy.du
  tests/dicts/exists.du
  tests/dicts/get.du
  tests/dicts/remove.du
  tests/dicts/subscript.du
Labels: bug fix, enhancement

#168 Break statement
  c/compiler.c
  c/compiler.h
  c/memory.c
  c/opcodes.h
  docs/docs/control-flow.md
  test.du
  tests/loops/break.du
  tests/loops/continue.du
  tests/loops/import.du
Labels: enhancement
