Repository dictu-lang/Dictu, pull requests merged in 2020-10, with the labels that each got.

#272 Add support for `_` as a delimiter in numbers.
  c/compiler.c
  c/scanner.c
  tests/maths/maths.du
  tests/number/toBool.du
  tests/number/toString.du
Labels: enhancement

#270 Fix import issue
  c/vm.c
Labels: bug fix

#274 Implement Random
  c/optionals/optionals.c
  c/optionals/optionals.h
  c/optionals/random.c
  c/optionals/random.h
  docs/docs/random.md
  docs/docs/sockets.md
  tests/random/import.du
  tests/random/random.du
  tests/random/range.du
  tests/random/select.du
Labels: enhancement

#267 List Destructuring
  c/compiler.c
  c/debug.c
  c/opcodes.h
  c/vm.c
  docs/docs/variables.md
  tests/variables/import.du
  tests/variables/list-unpacking.du
Labels: enhancement

#278 Fix compilation on Windows
  CMakeLists.txt
  c/common.h
  c/datatypes/files.c
  c/datatypes/number.c
  c/linenoise.c
  c/main.c
  c/memory.h
  c/opcodes.h
  c/optionals/c.c
  c/optionals/c.h
  c/optionals/datetime.c
  c/optionals/env.c
  c/optionals/http.c
  c/optionals/json.c
  c/optionals/jsonParseLib.c
  c/optionals/optionals.c
  c/optionals/optionals.h
  c/optionals/path.c
  c/optionals/path.h
  c/optionals/socket.c
  c/optionals/system.c
  c/optionals/system.h
  c/vm.c
  c/windowsapi.h
  docs/docs/datetime.md
  docs/docs/path.md
  docs/docs/system.md
  tests/datetime/strftime.du
  tests/datetime/strptime.du
  tests/files/seek.du
  tests/path/isdir.du
  tests/system/mkdir.du
  tests/system/process.du
  tests/system/remove.du
  tests/system/setCWD.du
Labels: enhancement

#276 Add Path.listdir() method
  c/optionals/path.c
  c/optionals/path.h
  docs/docs/path.md
  tests/path/listdir.du
  tests/path/test_dir/test_file_1
  tests/path/test_dir/test_file_2
  tests/path/test_dir/test_file_3
Labels: enhancement

#290 Add windows to Github Actions
  .github/workflows/main.yml
  CMakeLists.txt
  README.md
  docs/index.md
  tests/system/setCWD.du
Labels: bug fix, enhancement

#293 Implemented sin, cos, tan in math package.
  c/optionals/math.c
  docs/docs/math.md
  tests/maths/maths.du
Labels: enhancement

#298 Fix nested imports
  c/compiler.c
  c/vm.c
  tests/modules/functions.du
  tests/modules/variables.du
Labels: bug fix

#296 Fix an issue where multiple calls to the HTTP lib would segfault
  c/common.h
  c/memory.h
  c/optionals/http.c
  c/optionals/http.h
  c/table.c
  c/value.c
  c/vm.h
Labels: bug fix
