Repository dictu-lang/Dictu, pull requests merged in 2020-06, with the labels that each got.

#219 Suppress the compiler warnings for unused parameters.
  c.make
  c/chunk.c
  c/compiler.c
  c/datatypes/nil.c
  c/main.c
  c/natives.c
  c/optionals/jsonParseLib.c
  c/optionals/path.h
  c/optionals/system.c
  c/vm.h
Labels: enhancement

#218 Datetime
  Makefile
  c.make
  c/optionals/datetime.c
  c/optionals/datetime.h
  c/optionals/optionals.h
  c/vm.c
  c/vm.h
  docs/docs/datetime.md
  docs/docs/env.md
  docs/docs/http.md
  docs/docs/json.md
  docs/docs/math.md
  docs/docs/path.md
  docs/docs/system.md
  tests/datetime/import.du
  tests/datetime/strftime.du
  tests/datetime/strptime.du
  tests/runTests.du
Labels: enhancement

#221 Simplify some VM opcodes and fix issue with files
  c/vm.c
Labels: bug fix, enhancement

#222 Modules
  c/compiler.c
  c/compiler.h
  c/memory.c
  c/object.c
  c/object.h
  c/opcodes.h
  c/scanner.c
  c/scanner.h
  c/vm.c
  c/vm.h
  docs/docs/datetime.md
  docs/docs/env.md
  docs/docs/http.md
  docs/docs/json.md
  docs/docs/math.md
  docs/docs/modules.md
  docs/docs/path.md
  docs/docs/system.md
  tests/bool/toString.du
  tests/modules/classes.du
  tests/modules/functions.du
  tests/modules/import.du
  tests/modules/variables.du
  tests/runTests.du
Labels: bug fix, enhancement

#223 Create examples readme
  examples/README.md
  examples/fizzBuzz.du
  examples/guessingGame.du
Labels: enhancement

#224 Benchmarks
  tests/benchmarks/README.md
  tests/benchmarks/dict-methods/README.md
  tests/benchmarks/dict-methods/deepCopy.du
  tests/benchmarks/dict-methods/deepCopy.py
  tests/benchmarks/dict-methods/exists.du
  tests/benchmarks/dict-methods/exists.py
  tests/benchmarks/dict-methods/remove.du
  tests/benchmarks/dict-methods/remove.py
  tests/benchmarks/dict-methods/shallowCopy.du
  tests/benchmarks/dict-methods/shallowCopy.py
  tests/benchmarks/dictionaries.du
  tests/benchmarks/list-methods/README.md
  tests/benchmarks/list-methods/contains.du
  tests/benchmarks/list-methods/contains.py
  tests/benchmarks/list-methods/deepCopy.du
  tests/benchmarks/list-methods/deepCopy.py
  tests/benchmarks/list-methods/join.py
  tests/benchmarks/list-methods/pop.du
  tests/benchmarks/list-methods/pop.py
  tests/benchmarks/list-methods/push.du
  tests/benchmarks/list-methods/push.py
  tests/benchmarks/list-methods/shallowCopy.du
  tests/benchmarks/list-methods/shallowCopy.py
  tests/benchmarks/string-methods/README.md
  tests/benchmarks/string-methods/contains.du
  tests/benchmarks/string-methods/endsWith.du
  tests/benchmarks/string-methods/endsWith.py
  tests/benchmarks/string-methods/find.du
  tests/benchmarks/string-methods/find.py
  tests/benchmarks/string-methods/format.du
  tests/benchmarks/string-methods/format.py
  tests/benchmarks/string-methods/leftStrip.du
  tests/benchmarks/string-methods/leftStrip.py
  tests/benchmarks/string-methods/lower.du
  tests/benchmarks/string-methods/lower.py
  tests/benchmarks/string-methods/replace.du
  tests/benchmarks/string-methods/replace.py
  tests/benchmarks/string-methods/rightStrip.du
  tests/benchmarks/string-methods/rightStrip.py
  tests/benchmarks/string-methods/split.du
  tests/benchmarks/string-methods/split.py
  tests/benchmarks/string-methods/startsWith.du
  tests/benchmarks/string-methods/startsWith.py
  tests/benchmarks/string-methods/strip.du
  tests/benchmarks/string-methods/strip.py
  tests/benchmarks/string-methods/upper.du
  tests/benchmarks/string-methods/upper.py
  tests/system/time.du
Labels: enhancement

#227 Fix strftime() native method.
  c/optionals/datetime.c
  tests/datetime/strftime.du
Labels: bug fix

#228 Reset the module to the function on import end
  .github/workflows/main.yml
  c/vm.c
Labels: bug fix
