Repository dictu-lang/Dictu, pull requests merged in 2020-04, with the labels that each got.

#171 Add native class properties
  c/memory.c
  c/object.c
  c/object.h
  c/optionals/math.c
  c/util.c
  c/util.h
  c/vm.c
  docs/docs/math.md
  tests/maths/maths.du
Labels: enhancement

#173 Move argv magic variable into the System native class
  c/optionals/http.h
  c/optionals/system.c
  c/optionals/system.h
  c/vm.c
  docs/docs/getting-started.md
  docs/docs/system.md
  tests/system/constants.du
  tests/variables/import.du
Labels: enhancement

#169 Add Path Native class.
  c/optionals/optionals.h
  c/optionals/path.c
  c/optionals/path.h
  c/vm.c
  docs/docs/env.md
  docs/docs/http.md
  docs/docs/json.md
  docs/docs/path.md
  docs/docs/system.md
  test.du
  tests/path/path.du
  tests/runTests.du
Labels: enhancement

#175 Add System.platform constant, that identifies the underlying system p…
  c/optionals/system.c
  c/optionals/system.h
  docs/docs/system.md
  tests/system/constants.du
Labels: enhancement

#176 Len method
  c/datatypes/dicts.c
  c/datatypes/lists.c
  c/datatypes/sets.c
  c/datatypes/strings.c
  c/natives.c
  docs/docs/built-ins.md
  docs/docs/collections.md
  docs/docs/strings.md
  tests/builtins/import.du
  tests/builtins/len.du
  tests/dicts/import.du
  tests/dicts/len.du
  tests/http/get.du
  tests/http/post.du
  tests/lists/import.du
  tests/lists/insert.du
  tests/lists/len.du
  tests/lists/slicing.du
  tests/operators/equality.du
  tests/sets/add.du
  tests/sets/import.du
  tests/sets/len.du
  tests/sets/remove.du
  tests/strings/import.du
  tests/strings/len.du
  tests/strings/slicing.du
  tests/strings/subscript.du
  tests/system/getCWD.du
  tests/system/setCWD.du
Labels: enhancement

#177 Cleanup
  .github/workflows/main.yml
  c.make
  c/common.h
  c/datatypes/sets.c
  c/memory.c
  c/memory.h
  c/object.c
  c/object.h
  c/table.c
  c/value.c
  c/value.h
  c/vm.c
  tests/sets/add.du
  tests/sets/remove.du
Labels: bug fix, enhancement

#179 Create a stack for storing filenames
  c/compiler.c
  c/debug.c
  c/opcodes.h
  c/vm.c
  c/vm.h
Labels: bug fix

#182 Cleanup
  c/compiler.c
  c/debug.c
  c/natives.c
  c/optionals/http.c
  c/value.h
  c/vm.c
  tests/http/get.du
  tests/http/post.du
Labels: bug fix, enhancement

#185 Native methods
  c/datatypes/bool.c
  c/datatypes/bool.h
  c/datatypes/nil.c
  c/datatypes/nil.h
  c/datatypes/number.c
  c/datatypes/number.h
  c/memory.c
  c/vm.c
  c/vm.h
Labels: enhancement

#183 Add toString() method for ListType datatype.
  .github/workflows/main.yml
  c/datatypes/bool.c
  c/datatypes/dicts.c
  c/datatypes/lists.c
  c/datatypes/nil.c
  c/datatypes/number.c
  c/datatypes/sets.c
  c/natives.c
  c/object.c
  c/object.h
  c/value.c
  docs/docs/built-ins.md
  docs/docs/collections.md
  docs/docs/strings.md
  docs/docs/variables.md
  tests/bool/import.du
  tests/bool/toString.du
  tests/builtins/import.du
  tests/builtins/str.du
  tests/dicts/import.du
  tests/dicts/toString.du
  tests/lists/import.du
  tests/lists/toString.du
  tests/nil/import.du
  tests/nil/toString.du
  tests/number/import.du
  tests/number/toString.du
  tests/runTests.du
  tests/sets/toString.du
Labels: enhancement

#188 Convert builtin number() to string.toNumber()
  c/datatypes/sets.c
  c/datatypes/strings.c
  c/natives.c
  docs/docs/built-ins.md
  docs/docs/strings.md
  tests/builtins/import.du
  tests/builtins/number.du
  tests/strings/import.du
  tests/strings/toNumber.du
Labels: enhancement

#186 Rework toString
  c/object.c
  docs/docs/collections.md
  tests/dicts/toString.du
  tests/lists/toString.du
  tests/sets/import.du
  tests/sets/toString.du
Labels: bug fix, enhancement

#189 toString
  c/datatypes/class.c
  c/datatypes/class.h
  c/datatypes/instance.c
  c/memory.c
  c/object.c
  c/object.h
  c/vm.c
  c/vm.h
  docs/docs/classes.md
  tests/bool/toString.du
  tests/classes/import.du
  tests/classes/toString.du
  tests/dicts/toString.du
  tests/lists/toString.du
  tests/nil/toString.du
  tests/number/toString.du
Labels: enhancement

#190 toBool
  c/datatypes/dicts.c
  c/datatypes/lists.c
  c/datatypes/nil.c
  c/datatypes/number.c
  c/datatypes/sets.c
  c/datatypes/strings.c
  c/natives.c
  c/util.c
  c/util.h
  c/value.c
  docs/docs/built-ins.md
  docs/docs/collections.md
  docs/docs/strings.md
  docs/docs/variables.md
  tests/dicts/import.du
  tests/dicts/toBool.du
  tests/dicts/toString.du
  tests/lists/import.du
  tests/lists/toBool.du
  tests/nil/import.du
  tests/nil/toBool.du
  tests/number/import.du
  tests/number/toBool.du
  tests/sets/import.du
  tests/sets/toBool.du
  tests/sets/toString.du
  tests/strings/import.du
  tests/strings/toBool.du
Labels: bug fix, enhancement

#187 Raw strings
  c/compiler.c
  c/scanner.c
  c/scanner.h
  docs/docs/strings.md
  tests/strings/import.du
  tests/strings/rawStrings.du
Labels: bug fix, enhancement

#195 Hash tables
  c/memory.c
  c/object.h
  c/table.c
  c/table.h
  c/value.c
  c/vm.c
  tests/builtins/__file__.du
  tests/dicts/remove.du
Labels: enhancement

#197 Add System.remove() method, that deletes a file from the filesystem.
  c/optionals/system.c
  c/optionals/system.h
  docs/docs/system.md
  tests/system/import.du
  tests/system/remove.du
Labels: enhancement

#198 Add System.mkdir() and System.rmdir().
  c/optionals/system.c
  c/optionals/system.h
  docs/docs/system.md
  tests/system/mkdir.du
Labels: enhancement

#199 Release 0.5.1
  c/main.c
  c/memory.c
  c/object.h
  c/optionals/system.c
  c/optionals/system.h
  c/scanner.c
  c/table.c
  c/table.h
  c/value.c
  c/vm.c
  c/vm.h
  docs/_config.yml
  docs/docs/built-ins.md
  docs/docs/system.md
  tests/builtins/__file__.du
  tests/builtins/import.du
  tests/dicts/remove.du
  tests/system/import.du
  tests/system/mkdir.du
  tests/system/remove.du
  tests/system/setCWD.du
  tests/variables/import.du
Labels: release

#201 Add System.[getpid(),getppid(),getuid(),geteuid(),getgid(),getegid()]
  c/optionals/system.c
  docs/docs/system.md
  tests/system/import.du
  tests/system/mkdir.du
  tests/system/process.du
  tests/system/remove.du
Labels: enhancement

#200 Arrow functions
  c/compiler.c
  c/compiler.h
  c/scanner.c
  c/scanner.h
  docs/docs/control-flow.md
  tests/functions/arrow.du
  tests/functions/import.du
Labels: enhancement
