Repository dictu-lang/Dictu, pull requests merged in 2021-10, with the labels that each got.

#426 Update fibonacci example
  examples/fibonacci.du
  examples/recursiveFib.du
Labels: enhancement

#436 Remove ubuntu 16 from the workflow and add macos11
  .github/workflows/main.yml
Labels: bug fix

#433 Add `Path.join`
  docs/docs/standard-lib/path.md
  src/optionals/path.c
  tests/path/join.du
Labels: enhancement

#438 Update feature-report.md
  .github/ISSUE_TEMPLATE/feature-report.md
Labels: enhancement

#441 Update and rename feature-report.md to feature-report.yml
  .github/ISSUE_TEMPLATE/feature-report.md
  .github/ISSUE_TEMPLATE/feature-report.yml
Labels: enhancement

#444 Fix memory issue with `Path.join`
  src/optionals/path.c
  tests/path/import.du
  tests/path/join.du
Labels: bug fix

#443 obj.getAttribute()
  src/vm/datatypes/instance.c
  tests/classes/getAttributes.du
  tests/classes/import.du
Labels: enhancement

#453 Pop the value off the stack after printing and table resize
  src/vm/vm.c
Labels: bug fix

#451 Update so examples run as part of the CI/CD pipeline
  .github/workflows/main.yml
  examples/factorial.du
  examples/guessingGame.du
  examples/runExamples.du
Labels: enhancement

#454 Release 0.21.0
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-report.yml
  .github/pull_request_template.md
  .github/workflows/main.yml
  docs/_config.yml
  docs/docs/built-ins.md
  docs/docs/classes.md
  docs/docs/standard-lib/math.md
  docs/docs/standard-lib/path.md
  docs/docs/strings.md
  examples/factorial.du
  examples/fibonacci.du
  examples/guessingGame.du
  examples/recursiveFib.du
  examples/runExamples.du
  src/include/dictu_include.h
  src/optionals/math.c
  src/optionals/math.h
  src/optionals/path.c
  src/vm/compiler.c
  src/vm/compiler.h
  src/vm/datatypes/instance.c
  src/vm/datatypes/strings.c
  src/vm/debug.c
  src/vm/memory.c
  src/vm/natives.c
  src/vm/object.c
  src/vm/object.h
  src/vm/opcodes.h
  src/vm/scanner.c
  src/vm/scanner.h
  src/vm/value.c
  src/vm/value.h
  src/vm/vm.c
  tests/classes/annotations.du
  tests/classes/getAttributes.du
  tests/classes/import.du
  tests/maths/maths.du
  tests/path/import.du
  tests/path/join.du
  tests/strings/title.du
Labels: release

#446 Add path walker example
  examples/pathWalker.du
  examples/runExamples.du
Labels: enhancement

#459 Range of updates
  .github/workflows/main.yml
  docs/docs/control-flow.md
  docs/docs/standard-lib/math.md
  docs/docs/strings.md
  examples/README.md
  examples/design-patterns/README.md
  src/optionals/math.c
  src/vm/memory.c
  src/vm/vm.c
  tests/maths/maths.du
  tests/modules/from.du
Labels: enhancement

#448 list.findIndex()
  docs/docs/collections/lists.md
  src/vm/datatypes/lists/list-source.h
  src/vm/datatypes/lists/list.du
  tests/lists/find.du
  tests/lists/findIndex.du
  tests/lists/import.du
Labels: enhancement

#461 obj.getAttribute to return bound method rather than function
  src/vm/datatypes/instance.c
Labels: bug fix
