Repository dictu-lang/Dictu, pull requests merged in 2021-12, with the labels that each got.

#475 Add _class attribute to instances
  docs/docs/classes.md
  src/vm/object.c
  tests/classes/properties.du
Labels: enhancement

#488 add Code of Conduct
  CODE_OF_CONDUCT.md
Labels: enhancement

#497 Fix System.access() tests
  tests/system/access.du
  tests/system/import.du
Labels: bug fix

#492 Only allowing the word 'not' for logical negation
  .gitignore
  examples/pathWalker.du
  src/optionals/unittest/unittest.du
  src/vm/compiler.c
  src/vm/scanner.c
  src/vm/scanner.h
  tests/benchmarks/dict-methods/exists.du
  tests/benchmarks/methodCall.du
  tests/classes/copy.du
  tests/classes/isInstance.du
  tests/classes/methods.du
  tests/classes/properties.du
  tests/dicts/exists.du
  tests/lists/contains.du
  tests/operators/equality.du
  tests/operators/not.du
  tests/operators/ternary.du
  tests/result/matchWrap.du
  tests/sets/remove.du
  tests/strings/contains.du
  tests/strings/endsWith.du
  tests/strings/startsWith.du
  tests/system/access.du
Labels: enhancement

#483 initial log module impl
  docs/docs/standard-lib/log.md
  src/optionals/log.c
  src/optionals/log.h
  src/optionals/optionals.c
  src/optionals/optionals.h
  src/vm/natives.c
  tests/log/import.du
  tests/log/log.du
  tests/runTests.du
Labels: enhancement

#489 Add optional argument to split
  docs/docs/strings.md
  src/vm/datatypes/strings.c
  tests/strings/split.du
Labels: enhancement

#496 Env.readFile()
  .gitignore
  docs/docs/standard-lib/env.md
  scripts/generate.du
  src/optionals/env/env-source.h
  src/optionals/env/env.c
  src/optionals/env/env.du
  src/optionals/env/env.h
  src/optionals/optionals.c
  src/optionals/optionals.h
  src/vm/vm.c
  tests/env/.env
  tests/env/env.du
Labels: enhancement, bug fix

#484 add getAttributes to instances.c
  .gitignore
  docs/docs/classes.md
  src/vm/datatypes/instance.c
  tests/classes/getAttribute.du
  tests/classes/getAttributes.du
Labels: enhancement
