Repository dictu-lang/Dictu, pull requests merged in 2022-11, with the labels that each got.

#548 HTTP Client Implementation
  docs/docs/standard-lib/http.md
  examples/httpClient.du
  src/optionals/http/http.c
  tests/http/client.du
  tests/http/clientGet.du
  tests/http/clientPost.du
  tests/http/import.du
Labels: enhancement

#553 Release 0.26.0
  .github/workflows/main.yml
  README.md
  docs/_config.yml
  docs/docs/built-ins.md
  docs/docs/classes.md
  docs/docs/collections/sets.md
  docs/docs/functions.md
  docs/docs/standard-lib/env.md
  docs/docs/standard-lib/http.md
  docs/docs/standard-lib/object.md
  docs/docs/standard-lib/system.md
  docs/docs/standard-lib/term.md
  docs/docs/strings.md
  examples/httpClient.du
  examples/mkdirTemp.du
  examples/reverse_proxy.du
  examples/system.du
  examples/term.du
  scripts/checkTests.du
  scripts/generate.du
  src/include/dictu_include.h
  src/optionals/env/env.c
  src/optionals/http/http.c
  src/optionals/object/object-source.h
  src/optionals/object/object.c
  src/optionals/object/object.du
  src/optionals/object/object.h
  src/optionals/optionals.c
  src/optionals/optionals.h
  src/optionals/system.c
  src/optionals/term.c
  src/optionals/term.h
  src/vm/compiler.c
  src/vm/datatypes/sets.c
  src/vm/datatypes/strings.c
  src/vm/debug.c
  src/vm/object.c
  src/vm/vm.c
  tests/classes/properties.du
  tests/env/env.du
  tests/http/client.du
  tests/http/clientGet.du
  tests/http/clientPost.du
  tests/http/import.du
  tests/object/createFrom.du
  tests/object/import.du
  tests/operators/unpack.du
  tests/runTests.du
  tests/sets/containsAll.du
  tests/sets/import.du
  tests/strings/import.du
  tests/strings/repeat.du
  tests/system/import.du
  tests/system/mkdirTemp.du
  tests/system/uname.du
  tests/term/getSize.du
  tests/term/import.du
  tests/term/isatty.du
  tests/variables/list-unpacking.du
Labels: release

#565 Stop at non-option argparse
  src/cli/main.c
Labels: bug fix
